export type SeedMenuItem = {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: "signature" | "kahvalti" | "kahve" | "ferah";
  badge?: string;
  accent: "berry" | "cream" | "coffee" | "citrus" | "avocado";
  allergenInfo: string | null;
  estimatedCalories: number;
  priceInKurus: number;
  imageAlt: string;
  imagePath: string;
  isFeatured?: boolean;
};

export const seedMenuItems: SeedMenuItem[] = [
  {
    slug: "san-sebastian",
    name: "San Sebastian",
    description: "Karamelize üst, akışkan merkez ve bitter çikolata dokunuşu.",
    longDescription: "Yüksek ısıda karamelize edilen dış yüzeyin altında kalan yoğun, ipeksi ve hafif akışkan peynir kreması; bitter çikolata sosuyla servis edilir.",
    category: "signature",
    badge: "Bonj favorisi",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri, yumurta; eser miktarda gluten içerebilir.",
    estimatedCalories: 520,
    priceInKurus: 28500,
    imageAlt: "Karamelize yüzeyli San Sebastian cheesecake dilimi",
    imagePath: "public/images/menu/san-sebastian.webp",
    isFeatured: true,
  },
  {
    slug: "lotus-cheesecake",
    name: "Lotus Cheesecake",
    description: "Baharatlı bisküvi tabanı, ipeksi krema ve karamelize bisküvi sosu.",
    longDescription: "Tarçın ve karamel notalı bisküvi tabanı; dengeli peynir kreması ve parlak bisküvi sosuyla kat kat hazırlanır.",
    category: "signature",
    badge: "Çok sevilen",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 610,
    priceInKurus: 27500,
    imageAlt: "Karamelize bisküvi soslu Lotus cheesecake dilimi",
    imagePath: "public/images/menu/lotus-cheesecake.webp",
    isFeatured: true,
  },
  {
    slug: "oreo-cheesecake",
    name: "Oreo Cheesecake",
    description: "Kakaolu bisküvi tabanı, vanilyalı krema ve yoğun çikolata üst katmanı.",
    longDescription: "Kakaolu bisküvi kırıklarıyla zenginleştirilmiş vanilyalı cheesecake dolgusu, koyu bisküvi tabanı ve ince ganaj katmanıyla tamamlanır.",
    category: "signature",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 640,
    priceInKurus: 27500,
    imageAlt: "Kakaolu bisküvili ve ganajlı cheesecake dilimi",
    imagePath: "public/images/menu/oreo-cheesecake.webp",
  },
  {
    slug: "frambuaz-cheesecake",
    name: "Frambuaz Cheesecake",
    description: "Vanilyalı peynir kreması, canlı frambuaz sosu ve gevrek bisküvi tabanı.",
    longDescription: "Tatlı-ekşi frambuaz püresi, yumuşak vanilyalı peynir kremasını dengeler; üstünde taze frambuazlarla servis edilir.",
    category: "signature",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 490,
    priceInKurus: 27000,
    imageAlt: "Frambuaz soslu ve taze frambuazlı cheesecake dilimi",
    imagePath: "public/images/menu/frambuaz-cheesecake.webp",
  },
  {
    slug: "limon-cheesecake",
    name: "Limon Cheesecake",
    description: "Canlı narenciye notaları, hafif peynir kreması ve gevrek taban.",
    longDescription: "Taze limon suyu ve kabuğuyla hazırlanan parlak limon kreması, hafif peynir dolgusu ve tereyağlı bisküvi tabanıyla buluşur.",
    category: "signature",
    badge: "Ferah",
    accent: "citrus",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 470,
    priceInKurus: 26500,
    imageAlt: "Limon kremalı cheesecake dilimi",
    imagePath: "public/images/menu/limon-cheesecake.webp",
  },
  {
    slug: "cilek-cheesecake",
    name: "Çilek Cheesecake",
    description: "Taze çilek, vanilyalı krema ve tereyağlı bisküvi tabanı.",
    longDescription: "Mevsim çileklerinden hazırlanan doğal sos, ipeksi vanilyalı cheesecake dolgusu ve kıtır bisküvi tabanıyla servis edilir.",
    category: "signature",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 500,
    priceInKurus: 27000,
    imageAlt: "Taze çilekli ve çilek soslu cheesecake dilimi",
    imagePath: "public/images/menu/cilek-cheesecake.webp",
  },
  {
    slug: "yaban-mersinli-cheesecake",
    name: "Yaban Mersinli Cheesecake",
    description: "Yoğun yaban mersini kompostosu, vanilyalı krema ve gevrek taban.",
    longDescription: "Yaban mersininin doğal ekşiliği, dengeli vanilyalı peynir kremasıyla birleşir; meyve taneli kompostoyla tamamlanır.",
    category: "signature",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 505,
    priceInKurus: 27500,
    imageAlt: "Yaban mersini kompostolu cheesecake dilimi",
    imagePath: "public/images/menu/yaban-mersinli-cheesecake.webp",
  },
  {
    slug: "antep-fistikli-cheesecake",
    name: "Antep Fıstıklı Cheesecake",
    description: "Antep fıstığı kreması, ipeksi dolgu ve kıtır fıstık dokusu.",
    longDescription: "Gaziantep fıstığının kavruk ve aromatik karakteri; peynir kreması, fıstık ezmesi ve ince kıyılmış fıstıkla yoğunlaştırılır.",
    category: "signature",
    badge: "Gaziantep imzası",
    accent: "avocado",
    allergenInfo: "Antep fıstığı, gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 650,
    priceInKurus: 31000,
    imageAlt: "Antep fıstığı kremalı cheesecake dilimi",
    imagePath: "public/images/menu/antep-fistikli-cheesecake.webp",
    isFeatured: true,
  },
  {
    slug: "belcika-cikolatali-cheesecake",
    name: "Belçika Çikolatalı Cheesecake",
    description: "Yoğun bitter çikolata, kakaolu taban ve parlak ganaj.",
    longDescription: "Koyu kakao ve bitter çikolatayla hazırlanan yoğun cheesecake dolgusu, kakaolu taban ve ince ganaj katmanıyla tamamlanır.",
    category: "signature",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 680,
    priceInKurus: 29500,
    imageAlt: "Bitter çikolatalı ve ganajlı cheesecake dilimi",
    imagePath: "public/images/menu/belcika-cikolatali-cheesecake.webp",
  },
  {
    slug: "tuzlu-karamelli-cheesecake",
    name: "Tuzlu Karamelli Cheesecake",
    description: "Kehribar karamel, deniz tuzu ve vanilyalı peynir kreması.",
    longDescription: "Yavaş pişirilmiş karamel sosun tatlı-tuzlu dengesi, vanilyalı cheesecake dolgusu ve tereyağlı bisküvi tabanıyla buluşur.",
    category: "signature",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 620,
    priceInKurus: 28000,
    imageAlt: "Tuzlu karamel soslu cheesecake dilimi",
    imagePath: "public/images/menu/tuzlu-karamelli-cheesecake.webp",
  },
  {
    slug: "avokadolu-brunch-kruvasan",
    name: "Avokadolu Brunch Kruvasan",
    description: "Tereyağlı çıtır katlar; avokado, kremamsı scrambled egg, roka ve otlu labne.",
    longDescription: "Günlük pişen tereyağlı kruvasanın arasına olgun avokado, yumuşak scrambled egg, taze roka ve otlu labne eklenir.",
    category: "kahvalti",
    badge: "Bonj Brunch",
    accent: "avocado",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 690,
    priceInKurus: 34500,
    imageAlt: "Avokado, scrambled egg ve roka dolgulu kruvasan",
    imagePath: "public/images/menu/avokadolu-brunch-kruvasan.webp",
    isFeatured: true,
  },
  {
    slug: "fume-hindili-kruvasan",
    name: "Füme Hindili Kruvasan",
    description: "Füme hindi, cheddar, otlu labne, roka ve tereyağlı kruvasan.",
    longDescription: "Kat kat tereyağlı kruvasan; füme hindi, eriyen cheddar, otlu labne, roka ve ince domates dilimiyle sıcak servis edilir.",
    category: "kahvalti",
    accent: "cream",
    allergenInfo: "Gluten, süt ve süt ürünleri; eser miktarda yumurta içerebilir.",
    estimatedCalories: 720,
    priceInKurus: 33500,
    imageAlt: "Füme hindi ve cheddar dolgulu tereyağlı kruvasan",
    imagePath: "public/images/menu/fume-hindili-kruvasan.webp",
  },
  {
    slug: "espresso",
    name: "Double Espresso",
    description: "Yoğun gövde, kalıcı krema ve dengeli bitiş.",
    longDescription: "Çift shot olarak çekilen espresso; çekirdeğin çikolata, karamel ve kavruk yemiş notalarını kısa ve yoğun bir fincanda sunar.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 6,
    priceInKurus: 11000,
    imageAlt: "Yoğun kremalı double espresso",
    imagePath: "public/images/menu/espresso.webp",
  },
  {
    slug: "americano",
    name: "Americano",
    description: "Çift espresso ve sıcak suyla temiz, uzun içim.",
    longDescription: "Çift shot espressonun sıcak suyla açılmasıyla hazırlanan; aroması belirgin, gövdesi dengeli klasik uzun kahve.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 8,
    priceInKurus: 12500,
    imageAlt: "Seramik fincanda sıcak Americano",
    imagePath: "public/images/menu/americano.webp",
  },
  {
    slug: "flat-white",
    name: "Flat White",
    description: "Çift shot espresso ve kadifemsi mikro köpüğün dengesi.",
    longDescription: "Yoğun çift espresso, ince dokulu sıcak süt ve düşük köpük oranıyla kahve karakterini koruyan kadifemsi bir fincan.",
    category: "kahve",
    badge: "Barista seçimi",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 135,
    priceInKurus: 16500,
    imageAlt: "Rozetta latte artlı Flat White",
    imagePath: "public/images/menu/flat-white.webp",
    isFeatured: true,
  },
  {
    slug: "cappuccino",
    name: "Cappuccino",
    description: "Espresso, sıcak süt ve yoğun mikro köpükten klasik üçlü.",
    longDescription: "Tek shot espresso; eşit oranda sıcak süt ve ipeksi mikro köpükle dengelenir, hafif kakao dokunuşuyla tamamlanır.",
    category: "kahve",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 120,
    priceInKurus: 16000,
    imageAlt: "İpeksi köpüklü sıcak cappuccino",
    imagePath: "public/images/menu/cappuccino.webp",
  },
  {
    slug: "caffe-latte",
    name: "Caffè Latte",
    description: "Espresso, bol sıcak süt ve pürüzsüz mikro köpük.",
    longDescription: "Espressonun bol sıcak sütle yumuşatıldığı, ince mikro köpük katmanıyla tamamlanan uzun ve rahat içimli kahve.",
    category: "kahve",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 190,
    priceInKurus: 17000,
    imageAlt: "Cam bardakta katmanlı sıcak Caffè Latte",
    imagePath: "public/images/menu/caffe-latte.webp",
  },
  {
    slug: "mocha",
    name: "Mocha",
    description: "Espresso, bitter çikolata ve kadifemsi süt.",
    longDescription: "Yoğun espresso, bitter çikolata sosu ve sıcak sütün dengeli birleşimi; çikolata mermerli mikro köpükle tamamlanır.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: "Süt ve süt ürünleri, soya.",
    estimatedCalories: 290,
    priceInKurus: 18500,
    imageAlt: "Çikolata mermerli sıcak Mocha",
    imagePath: "public/images/menu/mocha.webp",
  },
  {
    slug: "cortado",
    name: "Cortado",
    description: "Eşit ölçü espresso ve sıcak sütle kısa, güçlü ve dengeli.",
    longDescription: "Espressonun aynı miktarda ipeksi sıcak sütle kesildiği; asiditesi yumuşak, kahve gövdesi belirgin kısa içim.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 75,
    priceInKurus: 14500,
    imageAlt: "Küçük cam bardakta katmanlı Cortado",
    imagePath: "public/images/menu/cortado.webp",
  },
  {
    slug: "v60",
    name: "V60",
    description: "Temiz gövde, parlak aroma ve çekirdeğe göre hassas demleme.",
    longDescription: "İnce kâğıt filtre ve kontrollü dairesel döküşle hazırlanan V60; çekirdeğin meyvemsi ve floral notalarını berrak bir fincanda öne çıkarır.",
    category: "kahve",
    badge: "3. nesil",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 5,
    priceInKurus: 19000,
    imageAlt: "Seramik dripper ve cam servisle V60 kahve",
    imagePath: "public/images/menu/v60.webp",
  },
  {
    slug: "chemex",
    name: "Chemex",
    description: "Berrak, zarif ve yumuşak içimli filtre kahve ritüeli.",
    longDescription: "Kalın filtre ve kontrollü demleme sayesinde tortusuz, temiz ve aromatik bir fincan; iki kişilik paylaşım servisine uygundur.",
    category: "kahve",
    badge: "Paylaşım",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 8,
    priceInKurus: 24000,
    imageAlt: "Cam Chemex demleme sürahisinde filtre kahve",
    imagePath: "public/images/menu/chemex.webp",
  },
  {
    slug: "cold-brew",
    name: "Cold Brew",
    description: "Uzun soğuk demleme, düşük asidite ve yoğun kahve aroması.",
    longDescription: "Kahvenin saatler boyunca soğuk suyla demlenmesiyle elde edilen; pürüzsüz, düşük asiditeli ve ferah yoğunlukta soğuk içim.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 10,
    priceInKurus: 17500,
    imageAlt: "Buzlu ve yoğun renkli Cold Brew kahve",
    imagePath: "public/images/menu/cold-brew.webp",
  },
  {
    slug: "iced-latte",
    name: "Iced Latte",
    description: "Yoğun espresso, soğuk süt ve her yudumda pürüzsüz bitiş.",
    longDescription: "Çift shot espresso; soğuk süt ve iri buzlarla katmanlanır, serin ve yumuşak bir kahve deneyimi sunar.",
    category: "kahve",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 180,
    priceInKurus: 18000,
    imageAlt: "Cam bardakta katmanlı ve buzlu Iced Latte",
    imagePath: "public/images/menu/iced-latte.webp",
  },
  {
    slug: "espresso-tonic",
    name: "Espresso Tonic",
    description: "Espresso, tonik, portakal kabuğu ve canlı kabarcıklar.",
    longDescription: "Buzlu tonik üzerine dökülen çift espresso; narenciye aroması, kahve acılığı ve canlı gazlı yapıyı tek bardakta buluşturur.",
    category: "kahve",
    badge: "Yeni nesil",
    accent: "citrus",
    allergenInfo: null,
    estimatedCalories: 85,
    priceInKurus: 19500,
    imageAlt: "Katmanlı espresso ve tonikli buzlu kahve",
    imagePath: "public/images/menu/espresso-tonic.webp",
  },
  {
    slug: "cilekli-limonata",
    name: "Çilekli Limonata",
    description: "Taze çilek, limon kabuğu ve dengeli ekşilikle buz gibi.",
    longDescription: "Taze sıkılmış limon, gerçek çilek püresi ve kontrollü şeker oranıyla günlük hazırlanır; iri buzlarla servis edilir.",
    category: "ferah",
    badge: "Taze",
    accent: "berry",
    allergenInfo: null,
    estimatedCalories: 170,
    priceInKurus: 16500,
    imageAlt: "Taze çilek parçalı buzlu çilekli limonata",
    imagePath: "public/images/menu/cilekli-limonata.webp",
  },
  {
    slug: "naneli-limonata",
    name: "Naneli Limonata",
    description: "Taze limon, ezilmiş nane ve ferah bir bitiş.",
    longDescription: "Günlük sıkılan limon suyu, taze nane yaprakları ve iri buzlarla hazırlanan canlı, aromatik ev yapımı limonata.",
    category: "ferah",
    accent: "avocado",
    allergenInfo: null,
    estimatedCalories: 145,
    priceInKurus: 15500,
    imageAlt: "Nane yapraklı ve buzlu ev yapımı limonata",
    imagePath: "public/images/menu/naneli-limonata.webp",
  },
  {
    slug: "hibiskus-cold-tea",
    name: "Hibiskus Cold Tea",
    description: "Hibiskus, kırmızı meyve notaları ve dengeli ekşilik.",
    longDescription: "Hibiskus çiçeğinin canlı rengi ve doğal ekşiliği; soğuk demleme yöntemiyle berrak, hafif ve ferah bir içeceğe dönüşür.",
    category: "ferah",
    accent: "berry",
    allergenInfo: null,
    estimatedCalories: 75,
    priceInKurus: 16500,
    imageAlt: "Koyu pembe hibiskuslu buzlu çay",
    imagePath: "public/images/menu/hibiskus-cold-tea.webp",
  },
  {
    slug: "iced-matcha-latte",
    name: "Iced Matcha Latte",
    description: "Seremoniyel matcha, soğuk süt ve dengeli bitkisel tat.",
    longDescription: "Çırpılarak pürüzsüzleştirilen matcha, soğuk süt ve iri buzlarla katmanlanır; taze, kremamsı ve uzun içimli bir alternatif sunar.",
    category: "ferah",
    badge: "Yeni",
    accent: "avocado",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 190,
    priceInKurus: 19500,
    imageAlt: "Yeşil matcha ve süt katmanlı buzlu latte",
    imagePath: "public/images/menu/iced-matcha-latte.webp",
  },
];
