export type SeedMenuItem = {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category:
    | "signature"
    | "tatli"
    | "kahvalti"
    | "bowl"
    | "kahve"
    | "soguk-kahve"
    | "ferah";
  badge?: string;
  accent: "berry" | "cream" | "coffee" | "citrus" | "avocado";
  allergenInfo: string | null;
  estimatedCalories: number;
  priceInKurus: number;
  imageAlt: string;
  imagePath: string;
  isFeatured?: boolean;
};

export const seedMenuItems: SeedMenuItem[] = [
  {
    slug: "san-sebastian",
    name: "San Sebastian",
    description: "Karamelize üst, akışkan merkez ve bitter çikolata dokunuşu.",
    longDescription: "Yüksek ısıda karamelize edilen dış yüzeyin altında kalan yoğun, ipeksi ve hafif akışkan peynir kreması; bitter çikolata sosuyla servis edilir.",
    category: "signature",
    badge: "Bonj favorisi",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri, yumurta; eser miktarda gluten içerebilir.",
    estimatedCalories: 520,
    priceInKurus: 28500,
    imageAlt: "Karamelize yüzeyli San Sebastian cheesecake dilimi",
    imagePath: "public/images/menu/san-sebastian.webp",
    isFeatured: true,
  },
  {
    slug: "lotus-cheesecake",
    name: "Lotus Cheesecake",
    description: "Baharatlı bisküvi tabanı, ipeksi krema ve karamelize bisküvi sosu.",
    longDescription: "Tarçın ve karamel notalı bisküvi tabanı; dengeli peynir kreması ve parlak bisküvi sosuyla kat kat hazırlanır.",
    category: "signature",
    badge: "Çok sevilen",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 610,
    priceInKurus: 27500,
    imageAlt: "Karamelize bisküvi soslu Lotus cheesecake dilimi",
    imagePath: "public/images/menu/lotus-cheesecake.webp",
    isFeatured: true,
  },
  {
    slug: "oreo-cheesecake",
    name: "Oreo Cheesecake",
    description: "Kakaolu bisküvi tabanı, vanilyalı krema ve yoğun çikolata üst katmanı.",
    longDescription: "Kakaolu bisküvi kırıklarıyla zenginleştirilmiş vanilyalı cheesecake dolgusu, koyu bisküvi tabanı ve ince ganaj katmanıyla tamamlanır.",
    category: "signature",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 640,
    priceInKurus: 27500,
    imageAlt: "Kakaolu bisküvili ve ganajlı cheesecake dilimi",
    imagePath: "public/images/menu/oreo-cheesecake.webp",
  },
  {
    slug: "frambuaz-cheesecake",
    name: "Frambuaz Cheesecake",
    description: "Vanilyalı peynir kreması, canlı frambuaz sosu ve gevrek bisküvi tabanı.",
    longDescription: "Tatlı-ekşi frambuaz püresi, yumuşak vanilyalı peynir kremasını dengeler; üstünde taze frambuazlarla servis edilir.",
    category: "signature",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 490,
    priceInKurus: 27000,
    imageAlt: "Frambuaz soslu ve taze frambuazlı cheesecake dilimi",
    imagePath: "public/images/menu/frambuaz-cheesecake.webp",
  },
  {
    slug: "limon-cheesecake",
    name: "Limon Cheesecake",
    description: "Canlı narenciye notaları, hafif peynir kreması ve gevrek taban.",
    longDescription: "Taze limon suyu ve kabuğuyla hazırlanan parlak limon kreması, hafif peynir dolgusu ve tereyağlı bisküvi tabanıyla buluşur.",
    category: "signature",
    badge: "Ferah",
    accent: "citrus",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 470,
    priceInKurus: 26500,
    imageAlt: "Limon kremalı cheesecake dilimi",
    imagePath: "public/images/menu/limon-cheesecake.webp",
  },
  {
    slug: "cilek-cheesecake",
    name: "Çilek Cheesecake",
    description: "Taze çilek, vanilyalı krema ve tereyağlı bisküvi tabanı.",
    longDescription: "Mevsim çileklerinden hazırlanan doğal sos, ipeksi vanilyalı cheesecake dolgusu ve kıtır bisküvi tabanıyla servis edilir.",
    category: "signature",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 500,
    priceInKurus: 27000,
    imageAlt: "Taze çilekli ve çilek soslu cheesecake dilimi",
    imagePath: "public/images/menu/cilek-cheesecake.webp",
  },
  {
    slug: "yaban-mersinli-cheesecake",
    name: "Yaban Mersinli Cheesecake",
    description: "Yoğun yaban mersini kompostosu, vanilyalı krema ve gevrek taban.",
    longDescription: "Yaban mersininin doğal ekşiliği, dengeli vanilyalı peynir kremasıyla birleşir; meyve taneli kompostoyla tamamlanır.",
    category: "signature",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 505,
    priceInKurus: 27500,
    imageAlt: "Yaban mersini kompostolu cheesecake dilimi",
    imagePath: "public/images/menu/yaban-mersinli-cheesecake.webp",
  },
  {
    slug: "antep-fistikli-cheesecake",
    name: "Antep Fıstıklı Cheesecake",
    description: "Antep fıstığı kreması, ipeksi dolgu ve kıtır fıstık dokusu.",
    longDescription: "Gaziantep fıstığının kavruk ve aromatik karakteri; peynir kreması, fıstık ezmesi ve ince kıyılmış fıstıkla yoğunlaştırılır.",
    category: "signature",
    badge: "Gaziantep imzası",
    accent: "avocado",
    allergenInfo: "Antep fıstığı, gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 650,
    priceInKurus: 31000,
    imageAlt: "Antep fıstığı kremalı cheesecake dilimi",
    imagePath: "public/images/menu/antep-fistikli-cheesecake.webp",
    isFeatured: true,
  },
  {
    slug: "belcika-cikolatali-cheesecake",
    name: "Belçika Çikolatalı Cheesecake",
    description: "Yoğun bitter çikolata, kakaolu taban ve parlak ganaj.",
    longDescription: "Koyu kakao ve bitter çikolatayla hazırlanan yoğun cheesecake dolgusu, kakaolu taban ve ince ganaj katmanıyla tamamlanır.",
    category: "signature",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 680,
    priceInKurus: 29500,
    imageAlt: "Bitter çikolatalı ve ganajlı cheesecake dilimi",
    imagePath: "public/images/menu/belcika-cikolatali-cheesecake.webp",
  },
  {
    slug: "tuzlu-karamelli-cheesecake",
    name: "Tuzlu Karamelli Cheesecake",
    description: "Kehribar karamel, deniz tuzu ve vanilyalı peynir kreması.",
    longDescription: "Yavaş pişirilmiş karamel sosun tatlı-tuzlu dengesi, vanilyalı cheesecake dolgusu ve tereyağlı bisküvi tabanıyla buluşur.",
    category: "signature",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 620,
    priceInKurus: 28000,
    imageAlt: "Tuzlu karamel soslu cheesecake dilimi",
    imagePath: "public/images/menu/tuzlu-karamelli-cheesecake.webp",
  },
  {
    slug: "avokadolu-brunch-kruvasan",
    name: "Avokadolu Brunch Kruvasan",
    description: "Tereyağlı çıtır katlar; avokado, kremamsı scrambled egg, roka ve otlu labne.",
    longDescription: "Günlük pişen tereyağlı kruvasanın arasına olgun avokado, yumuşak scrambled egg, taze roka ve otlu labne eklenir.",
    category: "kahvalti",
    badge: "Bonj Brunch",
    accent: "avocado",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 690,
    priceInKurus: 34500,
    imageAlt: "Avokado, scrambled egg ve roka dolgulu kruvasan",
    imagePath: "public/images/menu/avokadolu-brunch-kruvasan.webp",
    isFeatured: true,
  },
  {
    slug: "fume-hindili-kruvasan",
    name: "Füme Hindili Kruvasan",
    description: "Füme hindi, cheddar, otlu labne, roka ve tereyağlı kruvasan.",
    longDescription: "Kat kat tereyağlı kruvasan; füme hindi, eriyen cheddar, otlu labne, roka ve ince domates dilimiyle sıcak servis edilir.",
    category: "kahvalti",
    accent: "cream",
    allergenInfo: "Gluten, süt ve süt ürünleri; eser miktarda yumurta içerebilir.",
    estimatedCalories: 720,
    priceInKurus: 33500,
    imageAlt: "Füme hindi ve cheddar dolgulu tereyağlı kruvasan",
    imagePath: "public/images/menu/fume-hindili-kruvasan.webp",
  },
  {
    slug: "espresso",
    name: "Double Espresso",
    description: "Yoğun gövde, kalıcı krema ve dengeli bitiş.",
    longDescription: "Çift shot olarak çekilen espresso; çekirdeğin çikolata, karamel ve kavruk yemiş notalarını kısa ve yoğun bir fincanda sunar.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 6,
    priceInKurus: 11000,
    imageAlt: "Yoğun kremalı double espresso",
    imagePath: "public/images/menu/espresso.webp",
  },
  {
    slug: "americano",
    name: "Americano",
    description: "Çift espresso ve sıcak suyla temiz, uzun içim.",
    longDescription: "Çift shot espressonun sıcak suyla açılmasıyla hazırlanan; aroması belirgin, gövdesi dengeli klasik uzun kahve.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 8,
    priceInKurus: 12500,
    imageAlt: "Seramik fincanda sıcak Americano",
    imagePath: "public/images/menu/americano.webp",
  },
  {
    slug: "flat-white",
    name: "Flat White",
    description: "Çift shot espresso ve kadifemsi mikro köpüğün dengesi.",
    longDescription: "Yoğun çift espresso, ince dokulu sıcak süt ve düşük köpük oranıyla kahve karakterini koruyan kadifemsi bir fincan.",
    category: "kahve",
    badge: "Barista seçimi",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 135,
    priceInKurus: 16500,
    imageAlt: "Rozetta latte artlı Flat White",
    imagePath: "public/images/menu/flat-white.webp",
    isFeatured: true,
  },
  {
    slug: "cappuccino",
    name: "Cappuccino",
    description: "Espresso, sıcak süt ve yoğun mikro köpükten klasik üçlü.",
    longDescription: "Tek shot espresso; eşit oranda sıcak süt ve ipeksi mikro köpükle dengelenir, hafif kakao dokunuşuyla tamamlanır.",
    category: "kahve",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 120,
    priceInKurus: 16000,
    imageAlt: "İpeksi köpüklü sıcak cappuccino",
    imagePath: "public/images/menu/cappuccino.webp",
  },
  {
    slug: "caffe-latte",
    name: "Caffè Latte",
    description: "Espresso, bol sıcak süt ve pürüzsüz mikro köpük.",
    longDescription: "Espressonun bol sıcak sütle yumuşatıldığı, ince mikro köpük katmanıyla tamamlanan uzun ve rahat içimli kahve.",
    category: "kahve",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 190,
    priceInKurus: 17000,
    imageAlt: "Cam bardakta katmanlı sıcak Caffè Latte",
    imagePath: "public/images/menu/caffe-latte.webp",
  },
  {
    slug: "mocha",
    name: "Mocha",
    description: "Espresso, bitter çikolata ve kadifemsi süt.",
    longDescription: "Yoğun espresso, bitter çikolata sosu ve sıcak sütün dengeli birleşimi; çikolata mermerli mikro köpükle tamamlanır.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: "Süt ve süt ürünleri, soya.",
    estimatedCalories: 290,
    priceInKurus: 18500,
    imageAlt: "Çikolata mermerli sıcak Mocha",
    imagePath: "public/images/menu/mocha.webp",
  },
  {
    slug: "cortado",
    name: "Cortado",
    description: "Eşit ölçü espresso ve sıcak sütle kısa, güçlü ve dengeli.",
    longDescription: "Espressonun aynı miktarda ipeksi sıcak sütle kesildiği; asiditesi yumuşak, kahve gövdesi belirgin kısa içim.",
    category: "kahve",
    accent: "coffee",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 75,
    priceInKurus: 14500,
    imageAlt: "Küçük cam bardakta katmanlı Cortado",
    imagePath: "public/images/menu/cortado.webp",
  },
  {
    slug: "v60",
    name: "V60",
    description: "Temiz gövde, parlak aroma ve çekirdeğe göre hassas demleme.",
    longDescription: "İnce kâğıt filtre ve kontrollü dairesel döküşle hazırlanan V60; çekirdeğin meyvemsi ve floral notalarını berrak bir fincanda öne çıkarır.",
    category: "kahve",
    badge: "3. nesil",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 5,
    priceInKurus: 19000,
    imageAlt: "Seramik dripper ve cam servisle V60 kahve",
    imagePath: "public/images/menu/v60.webp",
  },
  {
    slug: "chemex",
    name: "Chemex",
    description: "Berrak, zarif ve yumuşak içimli filtre kahve ritüeli.",
    longDescription: "Kalın filtre ve kontrollü demleme sayesinde tortusuz, temiz ve aromatik bir fincan; iki kişilik paylaşım servisine uygundur.",
    category: "kahve",
    badge: "Paylaşım",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 8,
    priceInKurus: 24000,
    imageAlt: "Cam Chemex demleme sürahisinde filtre kahve",
    imagePath: "public/images/menu/chemex.webp",
  },
  {
    slug: "cold-brew",
    name: "Cold Brew",
    description: "Uzun soğuk demleme, düşük asidite ve yoğun kahve aroması.",
    longDescription: "Kahvenin saatler boyunca soğuk suyla demlenmesiyle elde edilen; pürüzsüz, düşük asiditeli ve ferah yoğunlukta soğuk içim.",
    category: "soguk-kahve",
    accent: "coffee",
    allergenInfo: null,
    estimatedCalories: 10,
    priceInKurus: 17500,
    imageAlt: "Buzlu ve yoğun renkli Cold Brew kahve",
    imagePath: "public/images/menu/cold-brew.webp",
  },
  {
    slug: "iced-latte",
    name: "Iced Latte",
    description: "Yoğun espresso, soğuk süt ve her yudumda pürüzsüz bitiş.",
    longDescription: "Çift shot espresso; soğuk süt ve iri buzlarla katmanlanır, serin ve yumuşak bir kahve deneyimi sunar.",
    category: "soguk-kahve",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 180,
    priceInKurus: 18000,
    imageAlt: "Cam bardakta katmanlı ve buzlu Iced Latte",
    imagePath: "public/images/menu/iced-latte.webp",
  },
  {
    slug: "espresso-tonic",
    name: "Espresso Tonic",
    description: "Espresso, tonik, portakal kabuğu ve canlı kabarcıklar.",
    longDescription: "Buzlu tonik üzerine dökülen çift espresso; narenciye aroması, kahve acılığı ve canlı gazlı yapıyı tek bardakta buluşturur.",
    category: "soguk-kahve",
    badge: "Yeni nesil",
    accent: "citrus",
    allergenInfo: null,
    estimatedCalories: 85,
    priceInKurus: 19500,
    imageAlt: "Katmanlı espresso ve tonikli buzlu kahve",
    imagePath: "public/images/menu/espresso-tonic.webp",
  },
  {
    slug: "cilekli-limonata",
    name: "Çilekli Limonata",
    description: "Taze çilek, limon kabuğu ve dengeli ekşilikle buz gibi.",
    longDescription: "Taze sıkılmış limon, gerçek çilek püresi ve kontrollü şeker oranıyla günlük hazırlanır; iri buzlarla servis edilir.",
    category: "ferah",
    badge: "Taze",
    accent: "berry",
    allergenInfo: null,
    estimatedCalories: 170,
    priceInKurus: 16500,
    imageAlt: "Taze çilek parçalı buzlu çilekli limonata",
    imagePath: "public/images/menu/cilekli-limonata.webp",
  },
  {
    slug: "naneli-limonata",
    name: "Naneli Limonata",
    description: "Taze limon, ezilmiş nane ve ferah bir bitiş.",
    longDescription: "Günlük sıkılan limon suyu, taze nane yaprakları ve iri buzlarla hazırlanan canlı, aromatik ev yapımı limonata.",
    category: "ferah",
    accent: "avocado",
    allergenInfo: null,
    estimatedCalories: 145,
    priceInKurus: 15500,
    imageAlt: "Nane yapraklı ve buzlu ev yapımı limonata",
    imagePath: "public/images/menu/naneli-limonata.webp",
  },
  {
    slug: "hibiskus-cold-tea",
    name: "Hibiskus Cold Tea",
    description: "Hibiskus, kırmızı meyve notaları ve dengeli ekşilik.",
    longDescription: "Hibiskus çiçeğinin canlı rengi ve doğal ekşiliği; soğuk demleme yöntemiyle berrak, hafif ve ferah bir içeceğe dönüşür.",
    category: "ferah",
    accent: "berry",
    allergenInfo: null,
    estimatedCalories: 75,
    priceInKurus: 16500,
    imageAlt: "Koyu pembe hibiskuslu buzlu çay",
    imagePath: "public/images/menu/hibiskus-cold-tea.webp",
  },
  {
    slug: "iced-matcha-latte",
    name: "Iced Matcha Latte",
    description: "Seremoniyel matcha, soğuk süt ve dengeli bitkisel tat.",
    longDescription: "Çırpılarak pürüzsüzleştirilen matcha, soğuk süt ve iri buzlarla katmanlanır; taze, kremamsı ve uzun içimli bir alternatif sunar.",
    category: "soguk-kahve",
    badge: "Yeni",
    accent: "avocado",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 190,
    priceInKurus: 19500,
    imageAlt: "Yeşil matcha ve süt katmanlı buzlu latte",
    imagePath: "public/images/menu/iced-matcha-latte.webp",
  },
  {
    slug: "baklavali-san-sebastian",
    name: "Baklavalı San Sebastian",
    description: "Akışkan cheesecake, çıtır baklava katı ve bol Antep fıstığı.",
    longDescription: "Bonj'un karamelize San Sebastian dokusu; tereyağlı baklava kırıkları, ince bal şerbeti ve Gaziantep fıstığıyla yerel bir imzaya dönüşür.",
    category: "signature",
    badge: "Gaziantep imzası",
    accent: "avocado",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, Antep fıstığı.",
    estimatedCalories: 710,
    priceInKurus: 34500,
    imageAlt: "Baklava kırıkları ve Antep fıstığıyla servis edilen San Sebastian",
    imagePath: "public/images/menu/antep-fistikli-cheesecake.webp",
    isFeatured: true,
  },
  {
    slug: "beyaz-cikolatali-frambuaz-cheesecake",
    name: "Beyaz Çikolatalı Frambuaz Cheesecake",
    description: "Beyaz çikolata kreması, ekşi frambuaz ve kıtır bisküvi tabanı.",
    longDescription: "Kremamsı beyaz çikolata dolgusu, frambuazın canlı ekşiliği ve tereyağlı bisküvi tabanıyla dengeli, meyvemsi bir cheesecake.",
    category: "signature",
    badge: "Yeni",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 590,
    priceInKurus: 30500,
    imageAlt: "Frambuaz ve beyaz çikolata kremalı cheesecake dilimi",
    imagePath: "public/images/menu/frambuaz-cheesecake.webp",
  },
  {
    slug: "eggs-benedict-kruvasan",
    name: "Eggs Benedict Kruvasan",
    description: "Tereyağlı kruvasan, poşe yumurta, dana füme ve hollandez.",
    longDescription: "Çıtır kruvasan üzerine dana füme, akışkan poşe yumurta ve limonlu hollandez sos yerleştirilir; mikro yeşilliklerle tamamlanır.",
    category: "kahvalti",
    badge: "Brunch favorisi",
    accent: "cream",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta; hardal içerebilir.",
    estimatedCalories: 760,
    priceInKurus: 42500,
    imageAlt: "Poşe yumurta ve hollandez soslu Eggs Benedict kruvasan",
    imagePath: "public/images/menu/eggs-benedict-kruvasan.webp",
    isFeatured: true,
  },
  {
    slug: "somon-fume-kruvasan",
    name: "Somon Füme Kruvasan",
    description: "Somon füme, avokado, labne, kapari ve dereotlu çıtır kruvasan.",
    longDescription: "Tereyağlı kruvasan; somon füme, avokado dilimleri, otlu labne, kapari, salatalık ve taze dereotuyla serin ve dengeli hazırlanır.",
    category: "kahvalti",
    accent: "avocado",
    allergenInfo: "Balık, gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 680,
    priceInKurus: 46500,
    imageAlt: "Somon füme, avokado ve labne dolgulu kruvasan",
    imagePath: "public/images/menu/avokadolu-brunch-kruvasan.webp",
  },
  {
    slug: "dana-fume-scrambled-kruvasan",
    name: "Dana Füme Scrambled Kruvasan",
    description: "Dana füme, kremamsı scrambled egg, cheddar ve karamelize soğan.",
    longDescription: "Sıcak kruvasanın arasına dana füme, düşük ısıda pişmiş scrambled egg, cheddar, karamelize soğan ve roka eklenir.",
    category: "kahvalti",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 810,
    priceInKurus: 41500,
    imageAlt: "Dana füme, scrambled egg ve cheddar dolgulu kruvasan",
    imagePath: "public/images/menu/eggs-benedict-kruvasan.webp",
  },
  {
    slug: "burrata-pesto-kruvasan",
    name: "Burrata & Pesto Kruvasan",
    description: "Burrata, fesleğen pesto, domates konfi ve roka.",
    longDescription: "Kat kat kruvasan; kremamsı burrata, fesleğen pesto, yavaş pişmiş domates konfi, roka ve balzamik dokunuşla hazırlanır.",
    category: "kahvalti",
    badge: "Vejetaryen",
    accent: "avocado",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, çam fıstığı.",
    estimatedCalories: 740,
    priceInKurus: 39500,
    imageAlt: "Burrata, pesto ve domates dolgulu kruvasan",
    imagePath: "public/images/menu/avokadolu-brunch-kruvasan.webp",
  },
  {
    slug: "menemen-kruvasan",
    name: "Menemen Kruvasan",
    description: "Köz biberli menemen, Ezine peyniri ve çıtır kruvasan.",
    longDescription: "Klasik menemen; közlenmiş biber, domates, yumurta ve Ezine peyniriyle hazırlanıp sıcak tereyağlı kruvasanın içinde servis edilir.",
    category: "kahvalti",
    badge: "Bonj yorumu",
    accent: "citrus",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 700,
    priceInKurus: 36500,
    imageAlt: "Menemen ve Ezine peyniri dolgulu kruvasan",
    imagePath: "public/images/menu/fume-hindili-kruvasan.webp",
  },
  {
    slug: "bonj-kahvalti-tabagi",
    name: "Bonj Kahvaltı Tabağı",
    description: "Yumurta, peynir seçkisi, avokado, zeytin, söğüş ve sıcak kruvasan.",
    longDescription: "İki yumurta, yerel peynir seçkisi, avokado, domates-salatalık, zeytin, ev yapımı reçel, bal-kaymak ve sıcak mini kruvasanla eksiksiz kahvaltı tabağı.",
    category: "kahvalti",
    badge: "Doyurucu",
    accent: "cream",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta; susam ve sert kabuklu yemiş içerebilir.",
    estimatedCalories: 980,
    priceInKurus: 49500,
    imageAlt: "Peynir, yumurta, avokado ve kruvasan içeren Bonj kahvaltı tabağı",
    imagePath: "public/images/menu/bonj-kahvalti-tabagi.webp",
    isFeatured: true,
  },
  {
    slug: "avokado-pose-yumurta-toast",
    name: "Avokado & Poşe Yumurta Toast",
    description: "Ekşi maya, ezilmiş avokado, iki poşe yumurta ve chili yağı.",
    longDescription: "Izgara ekşi maya üzerine limonlu avokado, iki akışkan poşe yumurta, chili yağı, susam ve taze otlar eklenir.",
    category: "kahvalti",
    accent: "avocado",
    allergenInfo: "Gluten, yumurta, susam; eser miktarda süt ürünü içerebilir.",
    estimatedCalories: 610,
    priceInKurus: 38500,
    imageAlt: "Avokado ve iki poşe yumurtalı ekşi maya toast",
    imagePath: "public/images/menu/bonj-kahvalti-tabagi.webp",
  },
  {
    slug: "cilbir-eksi-maya",
    name: "Çılbır & Ekşi Maya",
    description: "Sarımsaklı süzme yoğurt, poşe yumurta, chili tereyağı ve ekşi maya.",
    longDescription: "İki poşe yumurta sarımsaklı süzme yoğurt üzerinde; isotlu tereyağı, taze otlar ve kızarmış ekşi maya ekmeğiyle servis edilir.",
    category: "kahvalti",
    badge: "Yerel dokunuş",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 560,
    priceInKurus: 34500,
    imageAlt: "Yoğurt ve chili tereyağı üzerinde poşe yumurtalı çılbır",
    imagePath: "public/images/menu/bonj-kahvalti-tabagi.webp",
  },
  {
    slug: "meyveli-pancake",
    name: "Orman Meyveli Pancake",
    description: "Bulut pancake, mascarpone, orman meyveleri ve akçaağaç şurubu.",
    longDescription: "Yumuşak pancake katları; vanilyalı mascarpone, taze orman meyveleri, badem krokan ve akçaağaç şurubuyla servis edilir.",
    category: "kahvalti",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, badem.",
    estimatedCalories: 790,
    priceInKurus: 37500,
    imageAlt: "Mascarpone ve orman meyveleriyle servis edilen pancake",
    imagePath: "public/images/menu/meyveli-pancake.webp",
  },
  {
    slug: "brioche-french-toast",
    name: "Brioche French Toast",
    description: "Karamelize brioche, muz, fındık pralin ve vanilyalı krema.",
    longDescription: "Tereyağında karamelize edilen kalın brioche dilimi; muz, fındık pralin, vanilyalı krema ve hafif tarçınla sıcak servis edilir.",
    category: "kahvalti",
    badge: "Tatlı kahvaltı",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, fındık.",
    estimatedCalories: 860,
    priceInKurus: 38500,
    imageAlt: "Muz, pralin ve vanilyalı kremalı brioche French toast",
    imagePath: "public/images/menu/meyveli-pancake.webp",
  },
  {
    slug: "acai-bowl",
    name: "Açaí Bowl",
    description: "Açaí, muz, orman meyveleri, granola ve fıstık ezmesi.",
    longDescription: "Yoğun açaí ve muz bazı; ev yapımı granola, taze meyveler, chia, Hindistan cevizi ve şekersiz fıstık ezmesiyle tamamlanır.",
    category: "bowl",
    badge: "Vegan",
    accent: "berry",
    allergenInfo: "Yer fıstığı, sert kabuklu yemişler; granola gluten içerebilir.",
    estimatedCalories: 520,
    priceInKurus: 36500,
    imageAlt: "Orman meyvesi, granola ve fıstık ezmeli açaí bowl",
    imagePath: "public/images/menu/acai-bowl.webp",
    isFeatured: true,
  },
  {
    slug: "granola-yogurt-bowl",
    name: "Granola & Yoğurt Bowl",
    description: "Süzme yoğurt, ev granolası, mevsim meyveleri ve bal.",
    longDescription: "Kremamsı süzme yoğurt; Bonj granolası, mevsim meyveleri, bal, chia ve kavrulmuş bademle dengeli bir kâsede buluşur.",
    category: "bowl",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri, gluten, badem ve sert kabuklu yemişler.",
    estimatedCalories: 460,
    priceInKurus: 32500,
    imageAlt: "Granola, meyve ve ballı süzme yoğurt bowl",
    imagePath: "public/images/menu/acai-bowl.webp",
  },
  {
    slug: "chia-puding-bowl",
    name: "Mango Chia Puding",
    description: "Hindistan cevizi sütlü chia, mango, çarkıfelek ve granola.",
    longDescription: "Gece dinlendirilmiş Hindistan cevizi sütlü chia puding; mango püresi, çarkıfelek, granola ve taze nane ile servis edilir.",
    category: "bowl",
    badge: "Vegan",
    accent: "citrus",
    allergenInfo: "Granola gluten ve sert kabuklu yemiş içerebilir.",
    estimatedCalories: 390,
    priceInKurus: 33500,
    imageAlt: "Mango ve çarkıfelekli chia puding bowl",
    imagePath: "public/images/menu/acai-bowl.webp",
  },
  {
    slug: "protein-brunch-bowl",
    name: "Protein Brunch Bowl",
    description: "Kinoa, avokado, yumurta, hellim, yeşillik ve tahinli sos.",
    longDescription: "Kinoa ve yeşillik tabanı; avokado, ızgara hellim, iki yumurta, domates, salatalık ve limonlu tahin sosla tamamlanır.",
    category: "bowl",
    badge: "Dengeli",
    accent: "avocado",
    allergenInfo: "Süt ve süt ürünleri, yumurta, susam.",
    estimatedCalories: 670,
    priceInKurus: 40500,
    imageAlt: "Kinoa, avokado, yumurta ve hellimli protein bowl",
    imagePath: "public/images/menu/bonj-kahvalti-tabagi.webp",
  },
  {
    slug: "tiramisu",
    name: "Klasik Tiramisu",
    description: "Mascarpone, espresso, kakao ve yumuşak savoiardi katları.",
    longDescription: "Taze espressoyla ıslatılmış savoiardi katları; hafif mascarpone kreması ve yoğun kakao dokusuyla klasik oranlarında hazırlanır.",
    category: "tatli",
    badge: "Klasik",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 510,
    priceInKurus: 28500,
    imageAlt: "Kakao kaplı katmanlı klasik tiramisu",
    imagePath: "public/images/menu/tiramisu.webp",
    isFeatured: true,
  },
  {
    slug: "belcika-cikolatali-brownie",
    name: "Belçika Çikolatalı Brownie",
    description: "Yoğun bitter çikolata, ince çıtır kabuk ve nemli merkez.",
    longDescription: "Belçika bitter çikolatasıyla hazırlanan yoğun brownie; deniz tuzu, çikolata sosu ve isteğe göre dondurmayla servis edilir.",
    category: "tatli",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 590,
    priceInKurus: 26500,
    imageAlt: "Yoğun ve nemli Belçika çikolatalı brownie",
    imagePath: "public/images/menu/bonj-firin-tatlilari.webp",
  },
  {
    slug: "antep-fistikli-cookie",
    name: "Antep Fıstıklı Cookie",
    description: "Yumuşak merkez, beyaz çikolata ve bol Gaziantep fıstığı.",
    longDescription: "Dışı hafif çıtır, içi yumuşak cookie; iri Antep fıstığı, beyaz çikolata parçaları ve bir tutam deniz tuzuyla günlük pişirilir.",
    category: "tatli",
    badge: "Günlük fırından",
    accent: "avocado",
    allergenInfo: "Antep fıstığı, gluten, süt ve süt ürünleri, yumurta, soya.",
    estimatedCalories: 440,
    priceInKurus: 19500,
    imageAlt: "Beyaz çikolata ve Antep fıstıklı kalın cookie",
    imagePath: "public/images/menu/bonj-firin-tatlilari.webp",
  },
  {
    slug: "frambuazli-magnolia",
    name: "Frambuazlı Magnolia",
    description: "Vanilyalı krema, frambuaz, muz ve kıtır bisküvi katları.",
    longDescription: "İpeksi vanilyalı pastacı kreması; frambuaz sosu, taze muz ve tereyağlı bisküvi kırıklarıyla hafif katlar halinde hazırlanır.",
    category: "tatli",
    accent: "berry",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 480,
    priceInKurus: 25500,
    imageAlt: "Frambuaz soslu ve bisküvili magnolia",
    imagePath: "public/images/menu/frambuaz-cheesecake.webp",
  },
  {
    slug: "paris-brest",
    name: "Paris-Brest",
    description: "Çıtır choux, fındık pralin kreması ve kavrulmuş badem.",
    longDescription: "Halka biçimli choux hamuru; ipeksi fındık pralin kreması, kavrulmuş badem ve pudra şekeriyle Fransız pastane klasiğine dönüşür.",
    category: "tatli",
    badge: "Patisserie",
    accent: "coffee",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta, fındık, badem.",
    estimatedCalories: 560,
    priceInKurus: 29500,
    imageAlt: "Fındık pralin kremalı halka Paris-Brest tatlısı",
    imagePath: "public/images/menu/bonj-firin-tatlilari.webp",
  },
  {
    slug: "limonlu-mereng-tart",
    name: "Limonlu Mereng Tart",
    description: "Keskin limon kreması, tereyağlı tart ve alevlenmiş mereng.",
    longDescription: "Kıtır tereyağlı tart tabanı; canlı limon kreması ve ipeksi İsviçre merengiyle tatlı-ekşi bir dengede hazırlanır.",
    category: "tatli",
    accent: "citrus",
    allergenInfo: "Gluten, süt ve süt ürünleri, yumurta.",
    estimatedCalories: 430,
    priceInKurus: 27500,
    imageAlt: "Alevlenmiş mereng ve limon kremalı tart",
    imagePath: "public/images/menu/limon-cheesecake.webp",
  },
  {
    slug: "piccolo-latte",
    name: "Piccolo Latte",
    description: "Ristretto ve az miktarda mikro köpüklü sütle küçük, dengeli fincan.",
    longDescription: "Yoğun ristretto, küçük bardakta kadifemsi mikro köpüklü sütle buluşur; flat white'tan kısa, cortado'dan daha yumuşak bir içim sunar.",
    category: "kahve",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 85,
    priceInKurus: 15500,
    imageAlt: "Küçük cam bardakta mikro köpüklü Piccolo Latte",
    imagePath: "public/images/menu/cortado.webp",
  },
  {
    slug: "white-chocolate-mocha",
    name: "White Chocolate Mocha",
    description: "Espresso, beyaz çikolata ve ipeksi süt.",
    longDescription: "Çift espresso; dengeli beyaz çikolata sosu ve sıcak sütle birleşir, ince mikro köpük ve kakao nibs ile tamamlanır.",
    category: "kahve",
    badge: "Tatlı içim",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri, soya.",
    estimatedCalories: 330,
    priceInKurus: 20500,
    imageAlt: "Beyaz çikolatalı sıcak mocha",
    imagePath: "public/images/menu/mocha.webp",
  },
  {
    slug: "iced-spanish-latte",
    name: "Iced Spanish Latte",
    description: "Çift espresso, yoğunlaştırılmış süt ve bol buz.",
    longDescription: "Çift shot espresso; süt ve kontrollü ölçüde yoğunlaştırılmış sütle katmanlanır, bol buz üzerinde kremamsı ve dengeli servis edilir.",
    category: "soguk-kahve",
    badge: "Çok sevilen",
    accent: "cream",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 240,
    priceInKurus: 21000,
    imageAlt: "Katmanlı ve buzlu Spanish Latte",
    imagePath: "public/images/menu/iced-latte.webp",
    isFeatured: true,
  },
  {
    slug: "salted-caramel-cold-brew",
    name: "Salted Caramel Cold Brew",
    description: "Soğuk demleme kahve, tuzlu karamel ve hafif cold foam.",
    longDescription: "Düşük asiditeli cold brew; ev yapımı tuzlu karamel ve ince süt köpüğüyle tamamlanır, kahve karakteri korunarak servis edilir.",
    category: "soguk-kahve",
    accent: "coffee",
    allergenInfo: "Süt ve süt ürünleri.",
    estimatedCalories: 185,
    priceInKurus: 21500,
    imageAlt: "Tuzlu karamel ve süt köpüklü buzlu cold brew",
    imagePath: "public/images/menu/cold-brew.webp",
  },
  {
    slug: "mango-passion-limonata",
    name: "Mango & Passion Limonata",
    description: "Mango, çarkıfelek, taze limon ve aromatik ferahlık.",
    longDescription: "Mango püresi ve çarkıfelek; günlük sıkılan limon suyu, soda ve bol buzla tropik, canlı bir limonataya dönüşür.",
    category: "ferah",
    badge: "Tropik",
    accent: "citrus",
    allergenInfo: null,
    estimatedCalories: 180,
    priceInKurus: 18500,
    imageAlt: "Mango ve çarkıfelekli buzlu limonata",
    imagePath: "public/images/menu/cilekli-limonata.webp",
  },
  {
    slug: "berry-yuzu-soda",
    name: "Berry Yuzu Soda",
    description: "Kırmızı meyveler, yuzu, soda ve taze fesleğen.",
    longDescription: "Kırmızı meyve püresi ve aromatik yuzu; soda, fesleğen ve bol buzla hafif, canlı ve gazlı bir imza içeceğe dönüşür.",
    category: "ferah",
    badge: "Bonj soda",
    accent: "berry",
    allergenInfo: null,
    estimatedCalories: 125,
    priceInKurus: 19000,
    imageAlt: "Kırmızı meyve ve yuzu aromalı buzlu soda",
    imagePath: "public/images/menu/hibiskus-cold-tea.webp",
  },
];
